---
- name: install libtool
  become: yes
  apt: pkg=libtool update_cache=no state=present

- name: install zlib1g-dev
  become: yes
  apt: pkg=zlib1g-dev update_cache=no state=present


- name: libglib2.0-dev
  become: yes
  apt: pkg=libglib2.0-dev update_cache=no state=present


- name: install dh-autoreconf
  become: yes
  apt: pkg=dh-autoreconf update_cache=no state=present

- name: get specialized qemu
  git: repo={{ qemu_repo }}
       dest={{ qemu_tmpdir }}

- name: remove if qemu already exists
  command: rm -rf {{ qemu_dir }}

- name: move qemu
  command: mv -f {{ qemu_tmpdir }}/{{ qemu_ver }} {{ qemu_dir }}

- name: remove qemu_tmpdir
  command: rm -rf {{ qemu_tmpdir }}

- name: configure qemu
  command: ./configure --enable-kvm --target-list=x86_64-softmmu --enable-vhost-net
           chdir={{ qemu_dir }}

- name: make qemu
  command: make chdir={{ qemu_dir }}
