---

# Ubuntu
- name: apply all base packages
  hosts: ubuntu_common
  remote_user: "{{ remote_user }}"
  roles:
    - ubuntu_common
  environment:
    http_proxy: "{{ http_proxy }}"
    https_proxy: "{{ https_proxy }}"

- name: install libvirt
  hosts: ubuntu_libvirt
  remote_user: "{{ remote_user }}"
  roles:
    - ubuntu_libvirt
  environment:
    http_proxy: "{{ http_proxy }}"
    https_proxy: "{{ https_proxy }}"

- name: install spp and qemu
  hosts: ubuntu_spp
  remote_user: "{{ remote_user }}"
  roles:
    - ubuntu_spp
  environment:
    http_proxy: "{{ http_proxy }}"
    https_proxy: "{{ https_proxy }}"

- name: install pktgen
  hosts: ubuntu_pktgen
  remote_user: "{{ remote_user }}"
  roles:
    - ubuntu_pktgen
  environment:
    http_proxy: "{{ http_proxy }}"
    https_proxy: "{{ https_proxy }}"

# CentOS 7
- name: apply all base packages
  hosts: centos7_common
  remote_user: "{{ remote_user }}"
  roles:
    - centos7_common
  environment:
    http_proxy: "{{ http_proxy }}"
    https_proxy: "{{ https_proxy }}"

- name: install libvirt
  hosts: centos7_libvirt
  remote_user: "{{ remote_user }}"
  roles:
    - centos7_libvirt
  environment:
    http_proxy: "{{ http_proxy }}"
    https_proxy: "{{ https_proxy }}"

- name: install spp and qemu
  hosts: centos7_spp
  remote_user: "{{ remote_user }}"
  roles:
    - centos7_spp
  environment:
    http_proxy: "{{ http_proxy }}"
    https_proxy: "{{ https_proxy }}"

#- name: install pktgen
#  hosts: centos7_pktgen
#  remote_user: "{{ remote_user }}"
#  roles:
#    - centos7_pktgen
#  environment:
#    http_proxy: "{{ http_proxy }}"
#    https_proxy: "{{ https_proxy }}"

# CentOS 6
- name: apply all base packages
  hosts: centos6_common
  remote_user: "{{ remote_user }}"
  roles:
    - centos6_common
  environment:
    http_proxy: "{{ http_proxy }}"
    https_proxy: "{{ https_proxy }}"

- name: install libvirt
  hosts: centos6_libvirt
  remote_user: "{{ remote_user }}"
  roles:
    - centos6_libvirt
  environment:
    http_proxy: "{{ http_proxy }}"
    https_proxy: "{{ https_proxy }}"

- name: install spp and qemu
  hosts: centos6_spp
  remote_user: "{{ remote_user }}"
  roles:
    - centos6_spp
  environment:
    http_proxy: "{{ http_proxy }}"
    https_proxy: "{{ https_proxy }}"
