---
# Deploys the whole application stack in this site.

- name: apply all base packages
  hosts: all
  remote_user: dpdk-user
  vars:
    install_dir: "{{ ansible_env.HOME }}/dpdk-home"
    dpdk_dir: "{{ install_dir }}/dpdk"
    netsniff_dir: "{{ install_dir }}/netsniff-ng"
    dpdk_target: x86_64-ivshmem-linuxapp-gcc
  roles:
    - common

- name: install dpdk
  hosts: dpdk1
  remote_user: dpdk-user
  vars:
    nr_hugepages: 1024
    uname_r: 4.4.0-22-generic
    install_dir: "{{ ansible_env.HOME }}/dpdk-home"
    dpdk_dir: "{{ install_dir }}/dpdk"
    dpdk_target: x86_64-ivshmem-linuxapp-gcc
  roles:
    - dpdk1

- name: install pktgen
  hosts: pktgen 
  remote_user: dpdk-user
  vars:
    nr_hugepages: 4096
    uname_r: 4.4.0-22-generic
    install_dir: "{{ ansible_env.HOME }}/dpdk-home"
    dpdk_dir: "{{ install_dir }}/dpdk"
    pktgen_dir: "{{ install_dir }}/pktgen-dpdk"
    dpdk_target: x86_64-ivshmem-linuxapp-gcc
  roles:
    - pktgen
