---
# Deploys the whole application stack in this site.

- name: apply all base packages
  hosts: all
  remote_user: dpdk 
  roles:
    - common

- name: install dpdk
  hosts: dpdk 
  remote_user: dpdk
  roles:
    - dpdk 

- name: install kvm 
  hosts: dpdk 
  remote_user: dpdk
  roles:
    - kvm

- name: install spp and qemu 
  hosts: spp
  remote_user: dpdk
  roles:
    - spp

- name: install pktgen
  hosts: pktgen 
  remote_user: dpdk
  roles:
    - pktgen
