---
# Deploys the whole application stack in this site.

- name: apply all base packages
  hosts: centos6_common
  remote_user: "{{ remote_user }}"
  roles:
    - centos6_common

- name: install libvirt
  hosts: centos6_libvirt
  remote_user: "{{ remote_user }}"
  roles:
    - centos6_libvirt

- name: install spp and qemu
  hosts: centos6_spp
  remote_user: "{{ remote_user }}"
  roles:
    - centos6_spp
