---
- name: get dpdk
  git: repo=http://dpdk.org/git/dpdk
       dest={{ dpdk_dir }}

  #- name: make dpdk
  #  command: make config T={{ dpdk_target }} chdir={{ dpdk_dir }}

- name: install dpdk
  command: make install T={{ dpdk_target }} chdir={{ dpdk_dir }}

  #- name: bind eth2 to dpdk uio_pci_generic driver
  #  become: yes
  #  command: python dpdk_nic_bind.py --bind=uio_pci_generic eth2 chdir={{ dpdk_dir }}/tools
  #
  #- name: bind eth2 to dpdk uio_pci_generic driver
  #  become: yes
  #  command: python dpdk_nic_bind.py --bind=uio_pci_generic eth3 chdir={{ dpdk_dir }}/tools
  #
  #- name: bind eth3 to dpdk uio_pci_generic driver
  #  become: yes
  #  command: python dpdk_nic_bind.py --bind=uio_pci_generic eth4 chdir={{ dpdk_dir }}/tools
  #
  #- name: bind eth4 to dpdk uio_pci_generic driver
  #  become: yes
  #  command: python dpdk_nic_bind.py --bind=uio_pci_generic eth5 chdir={{ dpdk_dir }}/tools
