#!/bin/bash

# Normal setup
#   different cores for each port.

if [ -z ${RTE_SDK} ] ; then
  echo "*** RTE_SDK is not set"
  exit
fi
sdk=${RTE_SDK}

if [ -z ${RTE_TARGET} ]; then
  echo "*** RTE_TARGET is not set"
  exit
else
  target=${RTE_TARGET}
fi

cmd=./app/${target}/pktgen

dpdk_opts="-c 0x1f  -n 2 --proc-type auto --log-level 7"
pktgen_opts="-T -P"
port_map="-m [1:2].0 -m [3:4].1"
load_file="-f themes/white-black.theme"
black_list=""

echo ${cmd} ${dpdk_opts} ${black_list} -- ${pktgen_opts} ${port_map} ${load_file}
sudo ${cmd} ${dpdk_opts} ${black_list} -- ${pktgen_opts} ${port_map} ${load_file}
stty sane
