---
- name: install libarchive-dev for archive.h
  become: yes
  apt: pkg=libarchive-dev update_cache=no state=present

- name: install build-essential
  become: yes
  apt: pkg=build-essential update_cache=no state=present

- name: put install_linux_headers.sh
  copy: src=templates/install_linux_headers.sh
        dest={{ install_dir }}
        mode=775

- name: install linux-headers
  become: yes
  command: sh install_linux_headers.sh chdir={{ install_dir }}

- name: git clone {{ dpdk_repo }}
  git: repo={{ dpdk_repo }}
       dest={{ dpdk_dir }}
       version={{ dpdk_ver }}

- name: install dpdk
  command: make install T={{ dpdk_target }} chdir={{ dpdk_dir }}

- name: put do_after_reboot.sh
  copy: src=templates/do_after_reboot.sh
        dest={{ install_dir }}
        mode=775

- name: put env.sh
  template: src=templates/env_dpdk.j2
            dest={{ install_dir }}/env.sh
            mode=775
