---
- name: get dpdk
  git: repo=http://dpdk.org/git/dpdk
       dest={{ dpdk_dir }}

- name: make dpdk
  command: make config T={{ dpdk_target }} chdir={{ dpdk_dir }}

- name: install dpdk
  command: make install T={{ dpdk_target }} chdir={{ dpdk_dir }}

  #- name: bind eth2 to dpdk uio_pci_generic driver
  #  become: yes
  #  command: python dpdk_nic_bind.py --bind=uio_pci_generic eth2 chdir={{ dpdk_dir }}/tools
  #
  #- name: bind eth3 to dpdk uio_pci_generic driver
  #  become: yes
  #  command: python dpdk_nic_bind.py --bind=uio_pci_generic eth3 chdir={{ dpdk_dir }}/tools
  #
  #- name: bind eth4 to dpdk uio_pci_generic driver
  #  become: yes
  #  command: python dpdk_nic_bind.py --bind=uio_pci_generic eth4 chdir={{ dpdk_dir }}/tools
  #
  #- name: bind eth5 to dpdk uio_pci_generic driver
  #  become: yes
  #  command: python dpdk_nic_bind.py --bind=uio_pci_generic eth5 chdir={{ dpdk_dir }}/tools

- name: get pktgen
  git: repo=http://dpdk.org/git/apps/pktgen-dpdk
       dest={{ pktgen_dir }}

- name: put original doit script
  copy: src=templates/doit dest={{ pktgen_dir }} mode=775

- name: put patch for pktgen-dpdk/app/pktgen-pcap.c
  copy: src=templates/pktgen-pcap.patch dest={{ pktgen_dir }}/app mode=664

- name: patch for pktgen-dpdk/app/pktgen-pcap.c
  command: sh -c "patch < pktgen-pcap.patch" chdir={{ pktgen_dir }}/app

- name: make pktgen
  command: make RTE_SDK={{ dpdk_dir }} RTE_TARGET={{ dpdk_target }} chdir={{ pktgen_dir }}
