---
- name: install libpcap-dev
  become: yes
  apt: pkg=libpcap-dev state=present

- name: install liblua5.3-dev
  become: yes
  apt: pkg=liblua5.3-dev state=present

- name: get pktgen
  git: repo={{ pktgen_repo }}
       dest={{ pktgen_dir }}
       version={{ pktgen_ver }}

- name: put doit script
  copy: src=templates/doit dest={{ pktgen_dir }} mode=775

- name: make pktgen
  command: make RTE_SDK={{ dpdk_dir }} RTE_TARGET={{ dpdk_target }} chdir={{ pktgen_dir }}
