---
- name: mkdir dpdk_home
  file: path={{ dpdk_home }} state=directory

- name: install libarchive-dev for archive.h
  become: yes
  apt: pkg=libarchive-dev update_cache=no state=present

- name: install build-essential
  become: yes
  apt: pkg=build-essential update_cache=no state=present

- name: put install_linux_headers.sh
  copy: src=templates/install_linux_headers.sh
        dest={{ dpdk_home }}
        mode=775

- name: install linux-headers
  become: yes
  command: sh install_linux_headers.sh chdir={{ dpdk_home }}

- name: git clone {{ dpdk_repo }}
  git: repo={{ dpdk_repo }}
       dest={{ dpdk_dir }}
       version={{ dpdk_ver }}

- name: install dpdk
  command: make install T={{ dpdk_target }} chdir={{ dpdk_dir }}

- name: put do_after_reboot.sh
  copy: src=templates/do_after_reboot.sh
        dest={{ dpdk_home }}
        mode=775

- name: put env.sh
  template: src=templates/env_dpdk.j2
            dest={{ dpdk_home }}/env.sh
            mode=775

- name: put update_bashrc.py for env.sh
  template: src=templates/update_bashrc.j2
            dest={{ dpdk_home }}/update_bashrc.py
            mode=775

- name: update .bashrc
  command: python update_bashrc.py chdir={{ dpdk_home }}
