---
- name: install mandated packages
  become: yes
  apt: name={{ item }} state=present update_cache=yes
  with_items:
    - git
    - curl
    - wget
    - python-pip
    - python3-pip
    - python-yaml
    - pkg-config
