---
# mandatory
- include: base.yml
- include: hugepage-setup.yml
- include: dpdk.yml
- include: docker.yml
- include: sshkey-setup.yml
- include: sudo-without-pw.yml

# optional
- include: nmon.yml
- include: tmux.yml
- include: vim-latest.yml
#- include: nvim.yml
- include: dein.yml
#- include: emacs.yml
